"""NBA season engine package (Ch1–Ch3 + Ch5 PlayerProjection)."""

from src.services.nba_season_engine.priors import (
    ENGINE_VERSION,
    MINUTE_GRID_SUM,
    PAPER_SIM_S_SET,
    PLAYER_YEAR_WEIGHTS,
    SITUATION_ALTITUDE_NET,
    SITUATION_B2B_NET,
    SITUATION_HOME_NET,
    SITUATION_NET_CAP,
    SITUATION_TRAVEL_NET,
    TEAM_CARRY_SHRINK,
    TEAM_REBASE_RESIDUAL_CAP,
    TRAVEL_TZ_BAND_MIN_HOURS,
)
from src.services.nba_season_engine.team_prior import (
    apply_team_carry_shrink,
    documentation as team_prior_documentation,
    get_team_prior,
    load_team_prior_pack,
)
from src.services.nba_season_engine.roster_minutes import (
    documentation as roster_minutes_documentation,
    get_rebased_team,
    get_team_minutes,
    load_minutes_grid,
    load_player_talent_pack,
    load_rebased_team_prior,
    load_transactions,
)
from src.services.nba_season_engine.player_projection import (
    VECTOR_KEYS,
    documentation as player_projection_documentation,
    get_player_projection,
    get_team_projections,
    load_player_projection_pack,
    team_pts_identity,
)
from src.services.nba_season_engine.situation import (
    apply_situation_for_game,
    apply_situation_to_player_projections,
    apply_situation_to_team,
    coefficients as situation_coefficients,
    documentation as situation_documentation,
    load_situation_pack,
    load_venues_pack,
)

__all__ = [
    "ENGINE_VERSION",
    "TEAM_CARRY_SHRINK",
    "TEAM_REBASE_RESIDUAL_CAP",
    "PLAYER_YEAR_WEIGHTS",
    "MINUTE_GRID_SUM",
    "PAPER_SIM_S_SET",
    "SITUATION_HOME_NET",
    "SITUATION_B2B_NET",
    "SITUATION_TRAVEL_NET",
    "SITUATION_ALTITUDE_NET",
    "SITUATION_NET_CAP",
    "TRAVEL_TZ_BAND_MIN_HOURS",
    "VECTOR_KEYS",
    "apply_team_carry_shrink",
    "get_team_prior",
    "load_team_prior_pack",
    "team_prior_documentation",
    "get_rebased_team",
    "get_team_minutes",
    "load_minutes_grid",
    "load_player_talent_pack",
    "load_rebased_team_prior",
    "load_transactions",
    "roster_minutes_documentation",
    "load_player_projection_pack",
    "get_player_projection",
    "get_team_projections",
    "team_pts_identity",
    "player_projection_documentation",
    "load_venues_pack",
    "load_situation_pack",
    "apply_situation_to_team",
    "apply_situation_to_player_projections",
    "apply_situation_for_game",
    "situation_coefficients",
    "situation_documentation",
]
