"""NBA season engine package (Ch1–Ch5 + Ch4 team KEI)."""

from src.services.nba_season_engine.priors import (
    ENGINE_VERSION,
    MINUTE_GRID_SUM,
    PAPER_SIM_S_SET,
    PLAYER_YEAR_WEIGHTS,
    SITUATION_TEAM_PTS_CAP,
    TEAM_CARRY_SHRINK,
    TEAM_REBASE_RESIDUAL_CAP,
)
from src.services.nba_season_engine.team_prior import (
    apply_team_carry_shrink,
    documentation as team_prior_documentation,
    get_team_prior,
    load_team_prior_pack,
)
from src.services.nba_season_engine.roster_minutes import (
    documentation as roster_minutes_documentation,
    get_rebased_team,
    get_team_minutes,
    load_minutes_grid,
    load_player_talent_pack,
    load_rebased_team_prior,
    load_transactions,
)
from src.services.nba_season_engine.player_projection import (
    VECTOR_KEYS,
    documentation as player_projection_documentation,
    get_player_projection,
    get_team_projections,
    load_player_projection_pack,
    team_pts_identity,
)
from src.services.nba_season_engine.situation import (
    apply_situation_player_projections,
    apply_situation_team_line,
    documentation as situation_documentation,
    get_team_game_flags,
    load_paper_sim,
    load_schedule_pack,
    load_situation_coeffs,
    load_venue_flags,
    situation_delta_pts,
)
from src.services.nba_season_engine.nba_kei import (
    LEAN_EDGE_PTS,
    PLAY_EDGE_PTS,
    compute_game_kei,
    documentation as nba_kei_documentation,
    kei_lines_for_dates,
    load_kei_pack,
    tag_from_edge,
)

__all__ = [
    "ENGINE_VERSION",
    "TEAM_CARRY_SHRINK",
    "TEAM_REBASE_RESIDUAL_CAP",
    "SITUATION_TEAM_PTS_CAP",
    "PLAYER_YEAR_WEIGHTS",
    "MINUTE_GRID_SUM",
    "PAPER_SIM_S_SET",
    "VECTOR_KEYS",
    "PLAY_EDGE_PTS",
    "LEAN_EDGE_PTS",
    "apply_team_carry_shrink",
    "get_team_prior",
    "load_team_prior_pack",
    "team_prior_documentation",
    "get_rebased_team",
    "get_team_minutes",
    "load_minutes_grid",
    "load_player_talent_pack",
    "load_rebased_team_prior",
    "load_transactions",
    "roster_minutes_documentation",
    "load_player_projection_pack",
    "get_player_projection",
    "get_team_projections",
    "team_pts_identity",
    "player_projection_documentation",
    "load_situation_coeffs",
    "load_schedule_pack",
    "load_venue_flags",
    "load_paper_sim",
    "get_team_game_flags",
    "situation_delta_pts",
    "apply_situation_team_line",
    "apply_situation_player_projections",
    "situation_documentation",
    "compute_game_kei",
    "load_kei_pack",
    "kei_lines_for_dates",
    "tag_from_edge",
    "nba_kei_documentation",
]
