/** Packaged 2026 pace + one structural tag per team (efficiency backbone priors). */
export type NflStructuralPaceRow = { pace: number; tag: string | null };
export const NFL_STRUCTURAL_PACE_2026: Record<string, NflStructuralPaceRow> = {
  "ARI": { pace: 1.019, tag: "Pass-lean O" },
  "ATL": { pace: 0.983, tag: null },
  "BAL": { pace: 0.907, tag: "Run-lean O" },
  "BUF": { pace: 1.021, tag: "Run-lean O" },
  "CAR": { pace: 0.949, tag: "Soft O index" },
  "CHI": { pace: 1.065, tag: null },
  "CIN": { pace: 0.995, tag: "Pass-lean O" },
  "CLE": { pace: 0.975, tag: "Elite D index" },
  "DAL": { pace: 1.046, tag: "Elite O index" },
  "DEN": { pace: 1.021, tag: "Elite D index" },
  "DET": { pace: 0.996, tag: "Pressure D" },
  "GB": { pace: 0.953, tag: "Elite O index" },
  "HOU": { pace: 1.032, tag: "Elite D index" },
  "IND": { pace: 0.959, tag: "Elite O index" },
  "JAX": { pace: 1.01, tag: "Elite D index" },
  "KC": { pace: 0.994, tag: "Pressure D" },
  "LAR": { pace: 1.016, tag: "Elite O index" },
  "LAC": { pace: 1.021, tag: "Elite D index" },
  "LV": { pace: 0.894, tag: "Soft O index" },
  "MIA": { pace: 0.894, tag: "Soft D index" },
  "MIN": { pace: 0.895, tag: "Elite D index" },
  "NE": { pace: 0.973, tag: "Pressure D" },
  "NO": { pace: 1.009, tag: "Elite D index" },
  "NYG": { pace: 1.024, tag: "Soft D index" },
  "NYJ": { pace: 0.957, tag: "Soft O index" },
  "PHI": { pace: 0.956, tag: "Elite D index" },
  "PIT": { pace: 0.925, tag: null },
  "SEA": { pace: 0.956, tag: "Run-lean O" },
  "SF": { pace: 1.002, tag: "Elite O index" },
  "TB": { pace: 1.01, tag: null },
  "TEN": { pace: 0.944, tag: "Soft O index" },
  "WAS": { pace: 0.928, tag: "Run-lean O" },
  "LA": { pace: 1.016, tag: "Elite O index" },
};
