import type { TeamDirectoryEntry } from "./types";

/** MLB — 30 clubs (Athletics keep OAK code while Sacramento transition settles). */
export const MLB_TEAM_DIRECTORY: TeamDirectoryEntry[] = [
  {
    slug: "ari",
    code: "ARI",
    name: "Arizona Diamondbacks",
    conference: "NL",
    division: "West",
    city: "Phoenix",
  },
  {
    slug: "atl",
    code: "ATL",
    name: "Atlanta Braves",
    conference: "NL",
    division: "East",
    city: "Atlanta",
  },
  {
    slug: "bal",
    code: "BAL",
    name: "Baltimore Orioles",
    conference: "AL",
    division: "East",
    city: "Baltimore",
  },
  {
    slug: "bos",
    code: "BOS",
    name: "Boston Red Sox",
    conference: "AL",
    division: "East",
    city: "Boston",
  },
  {
    slug: "chc",
    code: "CHC",
    name: "Chicago Cubs",
    conference: "NL",
    division: "Central",
    city: "Chicago",
  },
  {
    slug: "cws",
    code: "CWS",
    name: "Chicago White Sox",
    conference: "AL",
    division: "Central",
    city: "Chicago",
  },
  {
    slug: "cin",
    code: "CIN",
    name: "Cincinnati Reds",
    conference: "NL",
    division: "Central",
    city: "Cincinnati",
  },
  {
    slug: "cle",
    code: "CLE",
    name: "Cleveland Guardians",
    conference: "AL",
    division: "Central",
    city: "Cleveland",
  },
  {
    slug: "col",
    code: "COL",
    name: "Colorado Rockies",
    conference: "NL",
    division: "West",
    city: "Denver",
  },
  {
    slug: "det",
    code: "DET",
    name: "Detroit Tigers",
    conference: "AL",
    division: "Central",
    city: "Detroit",
  },
  {
    slug: "hou",
    code: "HOU",
    name: "Houston Astros",
    conference: "AL",
    division: "West",
    city: "Houston",
  },
  {
    slug: "kc",
    code: "KC",
    name: "Kansas City Royals",
    conference: "AL",
    division: "Central",
    city: "Kansas City",
  },
  {
    slug: "laa",
    code: "LAA",
    name: "Los Angeles Angels",
    conference: "AL",
    division: "West",
    city: "Anaheim",
  },
  {
    slug: "lad",
    code: "LAD",
    name: "Los Angeles Dodgers",
    conference: "NL",
    division: "West",
    city: "Los Angeles",
  },
  {
    slug: "mia",
    code: "MIA",
    name: "Miami Marlins",
    conference: "NL",
    division: "East",
    city: "Miami",
  },
  {
    slug: "mil",
    code: "MIL",
    name: "Milwaukee Brewers",
    conference: "NL",
    division: "Central",
    city: "Milwaukee",
  },
  {
    slug: "min",
    code: "MIN",
    name: "Minnesota Twins",
    conference: "AL",
    division: "Central",
    city: "Minneapolis",
  },
  {
    slug: "nym",
    code: "NYM",
    name: "New York Mets",
    conference: "NL",
    division: "East",
    city: "New York",
  },
  {
    slug: "nyy",
    code: "NYY",
    name: "New York Yankees",
    conference: "AL",
    division: "East",
    city: "New York",
  },
  {
    slug: "oak",
    code: "OAK",
    name: "Athletics",
    conference: "AL",
    division: "West",
    city: "Sacramento",
  },
  {
    slug: "phi",
    code: "PHI",
    name: "Philadelphia Phillies",
    conference: "NL",
    division: "East",
    city: "Philadelphia",
  },
  {
    slug: "pit",
    code: "PIT",
    name: "Pittsburgh Pirates",
    conference: "NL",
    division: "Central",
    city: "Pittsburgh",
  },
  {
    slug: "sd",
    code: "SD",
    name: "San Diego Padres",
    conference: "NL",
    division: "West",
    city: "San Diego",
  },
  {
    slug: "sf",
    code: "SF",
    name: "San Francisco Giants",
    conference: "NL",
    division: "West",
    city: "San Francisco",
  },
  {
    slug: "sea",
    code: "SEA",
    name: "Seattle Mariners",
    conference: "AL",
    division: "West",
    city: "Seattle",
  },
  {
    slug: "stl",
    code: "STL",
    name: "St. Louis Cardinals",
    conference: "NL",
    division: "Central",
    city: "St. Louis",
  },
  {
    slug: "tb",
    code: "TB",
    name: "Tampa Bay Rays",
    conference: "AL",
    division: "East",
    city: "St. Petersburg",
  },
  {
    slug: "tex",
    code: "TEX",
    name: "Texas Rangers",
    conference: "AL",
    division: "West",
    city: "Arlington",
  },
  {
    slug: "tor",
    code: "TOR",
    name: "Toronto Blue Jays",
    conference: "AL",
    division: "East",
    city: "Toronto",
  },
  {
    slug: "wsh",
    code: "WSH",
    name: "Washington Nationals",
    conference: "NL",
    division: "East",
    city: "Washington",
  },
];

/** NBA — 30 teams */
export const NBA_TEAM_DIRECTORY: TeamDirectoryEntry[] = [
  {
    slug: "atl",
    code: "ATL",
    name: "Atlanta Hawks",
    conference: "Eastern",
    division: "Southeast",
  },
  {
    slug: "bos",
    code: "BOS",
    name: "Boston Celtics",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "bkn",
    code: "BKN",
    name: "Brooklyn Nets",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "cha",
    code: "CHA",
    name: "Charlotte Hornets",
    conference: "Eastern",
    division: "Southeast",
  },
  {
    slug: "chi",
    code: "CHI",
    name: "Chicago Bulls",
    conference: "Eastern",
    division: "Central",
  },
  {
    slug: "cle",
    code: "CLE",
    name: "Cleveland Cavaliers",
    conference: "Eastern",
    division: "Central",
  },
  {
    slug: "dal",
    code: "DAL",
    name: "Dallas Mavericks",
    conference: "Western",
    division: "Southwest",
  },
  {
    slug: "den",
    code: "DEN",
    name: "Denver Nuggets",
    conference: "Western",
    division: "Northwest",
  },
  {
    slug: "det",
    code: "DET",
    name: "Detroit Pistons",
    conference: "Eastern",
    division: "Central",
  },
  {
    slug: "gsw",
    code: "GSW",
    name: "Golden State Warriors",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "hou",
    code: "HOU",
    name: "Houston Rockets",
    conference: "Western",
    division: "Southwest",
  },
  {
    slug: "ind",
    code: "IND",
    name: "Indiana Pacers",
    conference: "Eastern",
    division: "Central",
  },
  {
    slug: "lac",
    code: "LAC",
    name: "LA Clippers",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "lal",
    code: "LAL",
    name: "Los Angeles Lakers",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "mem",
    code: "MEM",
    name: "Memphis Grizzlies",
    conference: "Western",
    division: "Southwest",
  },
  {
    slug: "mia",
    code: "MIA",
    name: "Miami Heat",
    conference: "Eastern",
    division: "Southeast",
  },
  {
    slug: "mil",
    code: "MIL",
    name: "Milwaukee Bucks",
    conference: "Eastern",
    division: "Central",
  },
  {
    slug: "min",
    code: "MIN",
    name: "Minnesota Timberwolves",
    conference: "Western",
    division: "Northwest",
  },
  {
    slug: "nop",
    code: "NOP",
    name: "New Orleans Pelicans",
    conference: "Western",
    division: "Southwest",
  },
  {
    slug: "nyk",
    code: "NYK",
    name: "New York Knicks",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "okc",
    code: "OKC",
    name: "Oklahoma City Thunder",
    conference: "Western",
    division: "Northwest",
  },
  {
    slug: "orl",
    code: "ORL",
    name: "Orlando Magic",
    conference: "Eastern",
    division: "Southeast",
  },
  {
    slug: "phi",
    code: "PHI",
    name: "Philadelphia 76ers",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "phx",
    code: "PHX",
    name: "Phoenix Suns",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "por",
    code: "POR",
    name: "Portland Trail Blazers",
    conference: "Western",
    division: "Northwest",
  },
  {
    slug: "sac",
    code: "SAC",
    name: "Sacramento Kings",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "sas",
    code: "SAS",
    name: "San Antonio Spurs",
    conference: "Western",
    division: "Southwest",
  },
  {
    slug: "tor",
    code: "TOR",
    name: "Toronto Raptors",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "uta",
    code: "UTA",
    name: "Utah Jazz",
    conference: "Western",
    division: "Northwest",
  },
  {
    slug: "was",
    code: "WAS",
    name: "Washington Wizards",
    conference: "Eastern",
    division: "Southeast",
  },
];

/** NHL — 32 teams */
export const NHL_TEAM_DIRECTORY: TeamDirectoryEntry[] = [
  {
    slug: "ana",
    code: "ANA",
    name: "Anaheim Ducks",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "bos",
    code: "BOS",
    name: "Boston Bruins",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "buf",
    code: "BUF",
    name: "Buffalo Sabres",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "cgy",
    code: "CGY",
    name: "Calgary Flames",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "car",
    code: "CAR",
    name: "Carolina Hurricanes",
    conference: "Eastern",
    division: "Metropolitan",
  },
  {
    slug: "chi",
    code: "CHI",
    name: "Chicago Blackhawks",
    conference: "Western",
    division: "Central",
  },
  {
    slug: "col",
    code: "COL",
    name: "Colorado Avalanche",
    conference: "Western",
    division: "Central",
  },
  {
    slug: "cbj",
    code: "CBJ",
    name: "Columbus Blue Jackets",
    conference: "Eastern",
    division: "Metropolitan",
  },
  {
    slug: "dal",
    code: "DAL",
    name: "Dallas Stars",
    conference: "Western",
    division: "Central",
  },
  {
    slug: "det",
    code: "DET",
    name: "Detroit Red Wings",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "edm",
    code: "EDM",
    name: "Edmonton Oilers",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "fla",
    code: "FLA",
    name: "Florida Panthers",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "lak",
    code: "LAK",
    name: "Los Angeles Kings",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "min",
    code: "MIN",
    name: "Minnesota Wild",
    conference: "Western",
    division: "Central",
  },
  {
    slug: "mtl",
    code: "MTL",
    name: "Montreal Canadiens",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "nsh",
    code: "NSH",
    name: "Nashville Predators",
    conference: "Western",
    division: "Central",
  },
  {
    slug: "njd",
    code: "NJD",
    name: "New Jersey Devils",
    conference: "Eastern",
    division: "Metropolitan",
  },
  {
    slug: "nyi",
    code: "NYI",
    name: "New York Islanders",
    conference: "Eastern",
    division: "Metropolitan",
  },
  {
    slug: "nyr",
    code: "NYR",
    name: "New York Rangers",
    conference: "Eastern",
    division: "Metropolitan",
  },
  {
    slug: "ott",
    code: "OTT",
    name: "Ottawa Senators",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "phi",
    code: "PHI",
    name: "Philadelphia Flyers",
    conference: "Eastern",
    division: "Metropolitan",
  },
  {
    slug: "pit",
    code: "PIT",
    name: "Pittsburgh Penguins",
    conference: "Eastern",
    division: "Metropolitan",
  },
  {
    slug: "sj",
    code: "SJS",
    name: "San Jose Sharks",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "sea",
    code: "SEA",
    name: "Seattle Kraken",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "stl",
    code: "STL",
    name: "St. Louis Blues",
    conference: "Western",
    division: "Central",
  },
  {
    slug: "tb",
    code: "TBL",
    name: "Tampa Bay Lightning",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "tor",
    code: "TOR",
    name: "Toronto Maple Leafs",
    conference: "Eastern",
    division: "Atlantic",
  },
  {
    slug: "uta",
    code: "UTA",
    name: "Utah Hockey Club",
    conference: "Western",
    division: "Central",
  },
  {
    slug: "van",
    code: "VAN",
    name: "Vancouver Canucks",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "vgk",
    code: "VGK",
    name: "Vegas Golden Knights",
    conference: "Western",
    division: "Pacific",
  },
  {
    slug: "wsh",
    code: "WSH",
    name: "Washington Capitals",
    conference: "Eastern",
    division: "Metropolitan",
  },
  {
    slug: "wpg",
    code: "WPG",
    name: "Winnipeg Jets",
    conference: "Western",
    division: "Central",
  },
];

/** WNBA — 15 teams (2026 expansion: Portland Fire + Toronto Tempo) */
export const WNBA_TEAM_DIRECTORY: TeamDirectoryEntry[] = [
  { slug: "atl", code: "ATL", name: "Atlanta Dream", conference: "Eastern" },
  { slug: "chi", code: "CHI", name: "Chicago Sky", conference: "Eastern" },
  { slug: "con", code: "CON", name: "Connecticut Sun", conference: "Eastern" },
  { slug: "dal", code: "DAL", name: "Dallas Wings", conference: "Western" },
  {
    slug: "gsv",
    code: "GSV",
    name: "Golden State Valkyries",
    conference: "Western",
  },
  { slug: "ind", code: "IND", name: "Indiana Fever", conference: "Eastern" },
  { slug: "las", code: "LAS", name: "Las Vegas Aces", conference: "Western" },
  { slug: "la", code: "LA", name: "Los Angeles Sparks", conference: "Western" },
  { slug: "min", code: "MIN", name: "Minnesota Lynx", conference: "Western" },
  { slug: "ny", code: "NY", name: "New York Liberty", conference: "Eastern" },
  { slug: "phx", code: "PHX", name: "Phoenix Mercury", conference: "Western" },
  { slug: "por", code: "POR", name: "Portland Fire", conference: "Western" },
  { slug: "sea", code: "SEA", name: "Seattle Storm", conference: "Western" },
  { slug: "tor", code: "TOR", name: "Toronto Tempo", conference: "Eastern" },
  {
    slug: "wsh",
    code: "WSH",
    name: "Washington Mystics",
    conference: "Eastern",
  },
];
