import type { TeamDirectoryEntry } from "./types";

type T = [slug: string, code: string, name: string, conference: string];

function mapTeams(rows: T[]): TeamDirectoryEntry[] {
  return rows.map(([slug, code, name, conference]) => ({
    slug,
    code,
    name,
    conference,
  }));
}

/** FBS — full Power + Group of 5 + Independents (2025 alignment approx). */
export const CFB_TEAM_DIRECTORY: TeamDirectoryEntry[] = mapTeams([
  // SEC
  ["alabama", "ALA", "Alabama", "SEC"],
  ["arkansas", "ARK", "Arkansas", "SEC"],
  ["auburn", "AUB", "Auburn", "SEC"],
  ["florida", "FLA", "Florida", "SEC"],
  ["georgia", "UGA", "Georgia", "SEC"],
  ["kentucky", "UK", "Kentucky", "SEC"],
  ["lsu", "LSU", "LSU", "SEC"],
  ["mississippi-state", "MSST", "Mississippi State", "SEC"],
  ["missouri", "MIZ", "Missouri", "SEC"],
  ["ole-miss", "MISS", "Ole Miss", "SEC"],
  ["oklahoma", "OU", "Oklahoma", "SEC"],
  ["south-carolina", "SC", "South Carolina", "SEC"],
  ["tennessee", "TENN", "Tennessee", "SEC"],
  ["texas", "TEX", "Texas", "SEC"],
  ["texas-am", "TA&M", "Texas A&M", "SEC"],
  ["vanderbilt", "VAN", "Vanderbilt", "SEC"],
  // Big Ten
  ["illinois", "ILL", "Illinois", "Big Ten"],
  ["indiana", "IND", "Indiana", "Big Ten"],
  ["iowa", "IOWA", "Iowa", "Big Ten"],
  ["maryland", "MD", "Maryland", "Big Ten"],
  ["michigan", "MICH", "Michigan", "Big Ten"],
  ["michigan-state", "MSU", "Michigan State", "Big Ten"],
  ["minnesota", "MINN", "Minnesota", "Big Ten"],
  ["nebraska", "NEB", "Nebraska", "Big Ten"],
  ["northwestern", "NW", "Northwestern", "Big Ten"],
  ["ohio-state", "OSU", "Ohio State", "Big Ten"],
  ["oregon", "ORE", "Oregon", "Big Ten"],
  ["penn-state", "PSU", "Penn State", "Big Ten"],
  ["purdue", "PUR", "Purdue", "Big Ten"],
  ["rutgers", "RUT", "Rutgers", "Big Ten"],
  ["ucla", "UCLA", "UCLA", "Big Ten"],
  ["usc", "USC", "USC", "Big Ten"],
  ["washington", "WASH", "Washington", "Big Ten"],
  ["wisconsin", "WISC", "Wisconsin", "Big Ten"],
  // ACC
  ["boston-college", "BC", "Boston College", "ACC"],
  ["california", "CAL", "California", "ACC"],
  ["clemson", "CLEM", "Clemson", "ACC"],
  ["duke", "DUKE", "Duke", "ACC"],
  ["florida-state", "FSU", "Florida State", "ACC"],
  ["georgia-tech", "GT", "Georgia Tech", "ACC"],
  ["louisville", "LOU", "Louisville", "ACC"],
  ["miami", "MIA", "Miami", "ACC"],
  ["nc-state", "NCST", "NC State", "ACC"],
  ["north-carolina", "UNC", "North Carolina", "ACC"],
  ["pittsburgh", "PITT", "Pittsburgh", "ACC"],
  ["smu", "SMU", "SMU", "ACC"],
  ["stanford", "STAN", "Stanford", "ACC"],
  ["syracuse", "SYR", "Syracuse", "ACC"],
  ["virginia", "UVA", "Virginia", "ACC"],
  ["virginia-tech", "VT", "Virginia Tech", "ACC"],
  ["wake-forest", "WAKE", "Wake Forest", "ACC"],
  // Big 12
  ["arizona", "ARIZ", "Arizona", "Big 12"],
  ["arizona-state", "ASU", "Arizona State", "Big 12"],
  ["baylor", "BAY", "Baylor", "Big 12"],
  ["byu", "BYU", "BYU", "Big 12"],
  ["cincinnati", "CIN", "Cincinnati", "Big 12"],
  ["colorado", "COLO", "Colorado", "Big 12"],
  ["houston", "HOU", "Houston", "Big 12"],
  ["iowa-state", "ISU", "Iowa State", "Big 12"],
  ["kansas", "KU", "Kansas", "Big 12"],
  ["kansas-state", "KSU", "Kansas State", "Big 12"],
  ["oklahoma-state", "OKST", "Oklahoma State", "Big 12"],
  ["tcu", "TCU", "TCU", "Big 12"],
  ["texas-tech", "TTU", "Texas Tech", "Big 12"],
  ["ucf", "UCF", "UCF", "Big 12"],
  ["utah", "UTAH", "Utah", "Big 12"],
  ["west-virginia", "WVU", "West Virginia", "Big 12"],
  // AAC
  ["army", "ARMY", "Army", "AAC"],
  ["charlotte", "CHAR", "Charlotte", "AAC"],
  ["east-carolina", "ECU", "East Carolina", "AAC"],
  ["florida-atlantic", "FAU", "Florida Atlantic", "AAC"],
  ["memphis", "MEM", "Memphis", "AAC"],
  ["navy", "NAVY", "Navy", "AAC"],
  ["north-texas", "UNT", "North Texas", "AAC"],
  ["rice", "RICE", "Rice", "AAC"],
  ["south-florida", "USF", "South Florida", "AAC"],
  ["temple", "TEM", "Temple", "AAC"],
  ["tulane", "TULN", "Tulane", "AAC"],
  ["tulsa", "TLSA", "Tulsa", "AAC"],
  ["uab", "UAB", "UAB", "AAC"],
  ["utsa", "UTSA", "UTSA", "AAC"],
  // Mountain West
  ["air-force", "AFA", "Air Force", "Mountain West"],
  ["boise-state", "BSU", "Boise State", "Mountain West"],
  ["colorado-state", "CSU", "Colorado State", "Mountain West"],
  ["fresno-state", "FRES", "Fresno State", "Mountain West"],
  ["hawaii", "HAW", "Hawaii", "Mountain West"],
  ["nevada", "NEV", "Nevada", "Mountain West"],
  ["new-mexico", "UNM", "New Mexico", "Mountain West"],
  ["san-diego-state", "SDSU", "San Diego State", "Mountain West"],
  ["san-jose-state", "SJSU", "San José State", "Mountain West"],
  ["unlv", "UNLV", "UNLV", "Mountain West"],
  ["utah-state", "USU", "Utah State", "Mountain West"],
  ["wyoming", "WYO", "Wyoming", "Mountain West"],
  // Sun Belt
  ["app-state", "APP", "App State", "Sun Belt"],
  ["arkansas-state", "ARST", "Arkansas State", "Sun Belt"],
  ["coastal-carolina", "CCU", "Coastal Carolina", "Sun Belt"],
  ["georgia-southern", "GASO", "Georgia Southern", "Sun Belt"],
  ["georgia-state", "GAST", "Georgia State", "Sun Belt"],
  ["james-madison", "JMU", "James Madison", "Sun Belt"],
  ["louisiana", "UL", "Louisiana", "Sun Belt"],
  ["marshall", "MRSH", "Marshall", "Sun Belt"],
  ["old-dominion", "ODU", "Old Dominion", "Sun Belt"],
  ["south-alabama", "USA", "South Alabama", "Sun Belt"],
  ["southern-miss", "USM", "Southern Miss", "Sun Belt"],
  ["texas-state", "TXST", "Texas State", "Sun Belt"],
  ["troy", "TROY", "Troy", "Sun Belt"],
  ["ulm", "ULM", "ULM", "Sun Belt"],
  // MAC
  ["akron", "AKR", "Akron", "MAC"],
  ["ball-state", "BALL", "Ball State", "MAC"],
  ["bowling-green", "BGSU", "Bowling Green", "MAC"],
  ["buffalo", "BUFF", "Buffalo", "MAC"],
  ["central-michigan", "CMU", "Central Michigan", "MAC"],
  ["eastern-michigan", "EMU", "Eastern Michigan", "MAC"],
  ["kent-state", "KENT", "Kent State", "MAC"],
  ["miami-oh", "M-OH", "Miami (OH)", "MAC"],
  ["northern-illinois", "NIU", "Northern Illinois", "MAC"],
  ["ohio", "OHIO", "Ohio", "MAC"],
  ["toledo", "TOL", "Toledo", "MAC"],
  ["western-michigan", "WMU", "Western Michigan", "MAC"],
  // CUSA
  ["florida-international", "FIU", "FIU", "CUSA"],
  ["jacksonville-state", "JVST", "Jacksonville State", "CUSA"],
  ["kennesaw-state", "KENN", "Kennesaw State", "CUSA"],
  ["liberty", "LIB", "Liberty", "CUSA"],
  ["louisiana-tech", "LT", "Louisiana Tech", "CUSA"],
  ["middle-tennessee", "MTSU", "Middle Tennessee", "CUSA"],
  ["new-mexico-state", "NMSU", "New Mexico State", "CUSA"],
  ["sam-houston", "SHSU", "Sam Houston", "CUSA"],
  ["utep", "UTEP", "UTEP", "CUSA"],
  ["western-kentucky", "WKU", "Western Kentucky", "CUSA"],
  // Independents
  ["connecticut", "CONN", "UConn", "Independent"],
  ["massachusetts", "MASS", "UMass", "Independent"],
  ["notre-dame", "ND", "Notre Dame", "Independent"],
]);

/**
 * CBB / NCAAM — Power 4 + Big East + major mid-majors commonly on betting boards.
 * Full D1 (~360) can extend this directory without changing page architecture.
 * Miami FL (ACC) and Miami OH (MAC) are distinct — never collapse.
 */
export const NCAAM_TEAM_DIRECTORY: TeamDirectoryEntry[] = mapTeams([
  // ACC
  ["boston-college", "BC", "Boston College", "ACC"],
  ["california", "CAL", "California", "ACC"],
  ["clemson", "CLEM", "Clemson", "ACC"],
  ["duke", "DUKE", "Duke", "ACC"],
  ["florida-state", "FSU", "Florida State", "ACC"],
  ["georgia-tech", "GT", "Georgia Tech", "ACC"],
  ["louisville", "LOU", "Louisville", "ACC"],
  ["miami-fl", "MIA", "Miami (FL)", "ACC"],
  ["nc-state", "NCST", "NC State", "ACC"],
  ["north-carolina", "UNC", "North Carolina", "ACC"],
  ["notre-dame", "ND", "Notre Dame", "ACC"],
  ["pittsburgh", "PITT", "Pittsburgh", "ACC"],
  ["smu", "SMU", "SMU", "ACC"],
  ["stanford", "STAN", "Stanford", "ACC"],
  ["syracuse", "SYR", "Syracuse", "ACC"],
  ["virginia", "UVA", "Virginia", "ACC"],
  ["virginia-tech", "VT", "Virginia Tech", "ACC"],
  ["wake-forest", "WAKE", "Wake Forest", "ACC"],
  // Big Ten
  ["illinois", "ILL", "Illinois", "Big Ten"],
  ["indiana", "IND", "Indiana", "Big Ten"],
  ["iowa", "IOWA", "Iowa", "Big Ten"],
  ["maryland", "MD", "Maryland", "Big Ten"],
  ["michigan", "MICH", "Michigan", "Big Ten"],
  ["michigan-state", "MSU", "Michigan State", "Big Ten"],
  ["minnesota", "MINN", "Minnesota", "Big Ten"],
  ["nebraska", "NEB", "Nebraska", "Big Ten"],
  ["northwestern", "NW", "Northwestern", "Big Ten"],
  ["ohio-state", "OSU", "Ohio State", "Big Ten"],
  ["oregon", "ORE", "Oregon", "Big Ten"],
  ["penn-state", "PSU", "Penn State", "Big Ten"],
  ["purdue", "PUR", "Purdue", "Big Ten"],
  ["rutgers", "RUT", "Rutgers", "Big Ten"],
  ["ucla", "UCLA", "UCLA", "Big Ten"],
  ["usc", "USC", "USC", "Big Ten"],
  ["washington", "WASH", "Washington", "Big Ten"],
  ["wisconsin", "WISC", "Wisconsin", "Big Ten"],
  // Big 12
  ["arizona", "ARIZ", "Arizona", "Big 12"],
  ["arizona-state", "ASU", "Arizona State", "Big 12"],
  ["baylor", "BAY", "Baylor", "Big 12"],
  ["byu", "BYU", "BYU", "Big 12"],
  ["cincinnati", "CIN", "Cincinnati", "Big 12"],
  ["colorado", "COLO", "Colorado", "Big 12"],
  ["houston", "HOU", "Houston", "Big 12"],
  ["iowa-state", "ISU", "Iowa State", "Big 12"],
  ["kansas", "KU", "Kansas", "Big 12"],
  ["kansas-state", "KSU", "Kansas State", "Big 12"],
  ["oklahoma-state", "OKST", "Oklahoma State", "Big 12"],
  ["tcu", "TCU", "TCU", "Big 12"],
  ["texas-tech", "TTU", "Texas Tech", "Big 12"],
  ["ucf", "UCF", "UCF", "Big 12"],
  ["utah", "UTAH", "Utah", "Big 12"],
  ["west-virginia", "WVU", "West Virginia", "Big 12"],
  // SEC
  ["alabama", "ALA", "Alabama", "SEC"],
  ["arkansas", "ARK", "Arkansas", "SEC"],
  ["auburn", "AUB", "Auburn", "SEC"],
  ["florida", "FLA", "Florida", "SEC"],
  ["georgia", "UGA", "Georgia", "SEC"],
  ["kentucky", "UK", "Kentucky", "SEC"],
  ["lsu", "LSU", "LSU", "SEC"],
  ["mississippi-state", "MSST", "Mississippi State", "SEC"],
  ["missouri", "MIZ", "Missouri", "SEC"],
  ["ole-miss", "MISS", "Ole Miss", "SEC"],
  ["oklahoma", "OU", "Oklahoma", "SEC"],
  ["south-carolina", "SC", "South Carolina", "SEC"],
  ["tennessee", "TENN", "Tennessee", "SEC"],
  ["texas", "TEX", "Texas", "SEC"],
  ["texas-am", "TA&M", "Texas A&M", "SEC"],
  ["vanderbilt", "VAN", "Vanderbilt", "SEC"],
  // Big East
  ["butler", "BUT", "Butler", "Big East"],
  ["creighton", "CREI", "Creighton", "Big East"],
  ["depaul", "DEP", "DePaul", "Big East"],
  ["georgetown", "GTWN", "Georgetown", "Big East"],
  ["marquette", "MARQ", "Marquette", "Big East"],
  ["providence", "PROV", "Providence", "Big East"],
  ["seton-hall", "HALL", "Seton Hall", "Big East"],
  ["st-johns", "SJU", "St. John's", "Big East"],
  ["uconn", "CONN", "UConn", "Big East"],
  ["villanova", "NOVA", "Villanova", "Big East"],
  ["xavier", "XAV", "Xavier", "Big East"],
  // MAC — Miami OH must exist so directory never collapses to Miami FL
  ["akron", "AKR", "Akron", "MAC"],
  ["ball-state", "BALL", "Ball State", "MAC"],
  ["bowling-green", "BGSU", "Bowling Green", "MAC"],
  ["buffalo", "BUFF", "Buffalo", "MAC"],
  ["central-michigan", "CMU", "Central Michigan", "MAC"],
  ["eastern-michigan", "EMU", "Eastern Michigan", "MAC"],
  ["kent-state", "KENT", "Kent State", "MAC"],
  ["miami-oh", "M-OH", "Miami (OH)", "MAC"],
  ["northern-illinois", "NIU", "Northern Illinois", "MAC"],
  ["ohio", "OHIO", "Ohio", "MAC"],
  ["toledo", "TOL", "Toledo", "MAC"],
  ["western-michigan", "WMU", "Western Michigan", "MAC"],
  // WCC / A-10 / MVC / AAC / MW / CUSA highlights
  ["gonzaga", "GONZ", "Gonzaga", "WCC"],
  ["saint-marys", "SMC", "Saint Mary's", "WCC"],
  ["san-diego", "USD", "San Diego", "WCC"],
  ["santa-clara", "SCU", "Santa Clara", "WCC"],
  ["loyola-marymount", "LMU", "Loyola Marymount", "WCC"],
  ["dayton", "DAY", "Dayton", "Atlantic 10"],
  ["vcu", "VCU", "VCU", "Atlantic 10"],
  ["saint-louis", "SLU", "Saint Louis", "Atlantic 10"],
  ["loyola-chicago", "L-IL", "Loyola Chicago", "Atlantic 10"],
  ["george-mason", "GMU", "George Mason", "Atlantic 10"],
  ["drake", "DRKE", "Drake", "MVC"],
  ["bradley", "BRAD", "Bradley", "MVC"],
  ["indiana-state", "INST", "Indiana State", "MVC"],
  ["murray-state", "MURR", "Murray State", "MVC"],
  ["memphis", "MEM", "Memphis", "AAC"],
  ["florida-atlantic", "FAU", "Florida Atlantic", "AAC"],
  ["north-texas", "UNT", "North Texas", "AAC"],
  ["wichita-state", "WICH", "Wichita State", "AAC"],
  ["tulane", "TULN", "Tulane", "AAC"],
  ["boise-state", "BSU", "Boise State", "Mountain West"],
  ["san-diego-state", "SDSU", "San Diego State", "Mountain West"],
  ["new-mexico", "UNM", "New Mexico", "Mountain West"],
  ["nevada", "NEV", "Nevada", "Mountain West"],
  ["unlv", "UNLV", "UNLV", "Mountain West"],
  ["fresno-state", "FRES", "Fresno State", "Mountain West"],
  ["san-jose-state", "SJSU", "San José State", "Mountain West"],
  ["colorado-state", "CSU", "Colorado State", "Mountain West"],
  ["grand-canyon", "GCU", "Grand Canyon", "WCC"],
  ["liberty", "LIB", "Liberty", "Conference USA"],
  ["western-kentucky", "WKU", "Western Kentucky", "Conference USA"],
  ["florida-international", "FIU", "FIU", "Conference USA"],
  ["jacksonville-state", "JVST", "Jacksonville State", "Conference USA"],
  ["florida-gulf-coast", "FGCU", "FGCU", "Atlantic Sun"],
  ["yale", "YALE", "Yale", "Ivy"],
  ["princeton", "PRIN", "Princeton", "Ivy"],
  ["harvard", "HARV", "Harvard", "Ivy"],
  ["mcneese", "MCN", "McNeese", "Southland"],
  ["app-state", "APP", "App State", "Sun Belt"],
  ["james-madison", "JMU", "James Madison", "Sun Belt"],
  ["charleston", "COFC", "Charleston", "CAA"],
]);
