import type { TeamDirectoryEntry } from "./types";

type T = [slug: string, code: string, name: string, conference: string];

function mapTeams(rows: T[]): TeamDirectoryEntry[] {
  return rows.map(([slug, code, name, conference]) => ({
    slug,
    code,
    name,
    conference,
  }));
}

/** FBS — full Power + Group of 5 + Independents (2025 alignment approx). */
export const CFB_TEAM_DIRECTORY: TeamDirectoryEntry[] = mapTeams([
  // SEC
  ["alabama", "ALA", "Alabama", "SEC"],
  ["arkansas", "ARK", "Arkansas", "SEC"],
  ["auburn", "AUB", "Auburn", "SEC"],
  ["florida", "FLA", "Florida", "SEC"],
  ["georgia", "UGA", "Georgia", "SEC"],
  ["kentucky", "UK", "Kentucky", "SEC"],
  ["lsu", "LSU", "LSU", "SEC"],
  ["mississippi-state", "MSST", "Mississippi State", "SEC"],
  ["missouri", "MIZ", "Missouri", "SEC"],
  ["ole-miss", "MISS", "Ole Miss", "SEC"],
  ["oklahoma", "OU", "Oklahoma", "SEC"],
  ["south-carolina", "SC", "South Carolina", "SEC"],
  ["tennessee", "TENN", "Tennessee", "SEC"],
  ["texas", "TEX", "Texas", "SEC"],
  ["texas-am", "TA&M", "Texas A&M", "SEC"],
  ["vanderbilt", "VAN", "Vanderbilt", "SEC"],
  // Big Ten
  ["illinois", "ILL", "Illinois", "Big Ten"],
  ["indiana", "IND", "Indiana", "Big Ten"],
  ["iowa", "IOWA", "Iowa", "Big Ten"],
  ["maryland", "MD", "Maryland", "Big Ten"],
  ["michigan", "MICH", "Michigan", "Big Ten"],
  ["michigan-state", "MSU", "Michigan State", "Big Ten"],
  ["minnesota", "MINN", "Minnesota", "Big Ten"],
  ["nebraska", "NEB", "Nebraska", "Big Ten"],
  ["northwestern", "NW", "Northwestern", "Big Ten"],
  ["ohio-state", "OSU", "Ohio State", "Big Ten"],
  ["oregon", "ORE", "Oregon", "Big Ten"],
  ["penn-state", "PSU", "Penn State", "Big Ten"],
  ["purdue", "PUR", "Purdue", "Big Ten"],
  ["rutgers", "RUT", "Rutgers", "Big Ten"],
  ["ucla", "UCLA", "UCLA", "Big Ten"],
  ["usc", "USC", "USC", "Big Ten"],
  ["washington", "WASH", "Washington", "Big Ten"],
  ["wisconsin", "WISC", "Wisconsin", "Big Ten"],
  // ACC
  ["boston-college", "BC", "Boston College", "ACC"],
  ["california", "CAL", "California", "ACC"],
  ["clemson", "CLEM", "Clemson", "ACC"],
  ["duke", "DUKE", "Duke", "ACC"],
  ["florida-state", "FSU", "Florida State", "ACC"],
  ["georgia-tech", "GT", "Georgia Tech", "ACC"],
  ["louisville", "LOU", "Louisville", "ACC"],
  ["miami", "MIA", "Miami", "ACC"],
  ["nc-state", "NCST", "NC State", "ACC"],
  ["north-carolina", "UNC", "North Carolina", "ACC"],
  ["pittsburgh", "PITT", "Pittsburgh", "ACC"],
  ["smu", "SMU", "SMU", "ACC"],
  ["stanford", "STAN", "Stanford", "ACC"],
  ["syracuse", "SYR", "Syracuse", "ACC"],
  ["virginia", "UVA", "Virginia", "ACC"],
  ["virginia-tech", "VT", "Virginia Tech", "ACC"],
  ["wake-forest", "WAKE", "Wake Forest", "ACC"],
  // Big 12
  ["arizona", "ARIZ", "Arizona", "Big 12"],
  ["arizona-state", "ASU", "Arizona State", "Big 12"],
  ["baylor", "BAY", "Baylor", "Big 12"],
  ["byu", "BYU", "BYU", "Big 12"],
  ["cincinnati", "CIN", "Cincinnati", "Big 12"],
  ["colorado", "COLO", "Colorado", "Big 12"],
  ["houston", "HOU", "Houston", "Big 12"],
  ["iowa-state", "ISU", "Iowa State", "Big 12"],
  ["kansas", "KU", "Kansas", "Big 12"],
  ["kansas-state", "KSU", "Kansas State", "Big 12"],
  ["oklahoma-state", "OKST", "Oklahoma State", "Big 12"],
  ["tcu", "TCU", "TCU", "Big 12"],
  ["texas-tech", "TTU", "Texas Tech", "Big 12"],
  ["ucf", "UCF", "UCF", "Big 12"],
  ["utah", "UTAH", "Utah", "Big 12"],
  ["west-virginia", "WVU", "West Virginia", "Big 12"],
  // AAC
  ["army", "ARMY", "Army", "AAC"],
  ["charlotte", "CHAR", "Charlotte", "AAC"],
  ["east-carolina", "ECU", "East Carolina", "AAC"],
  ["florida-atlantic", "FAU", "Florida Atlantic", "AAC"],
  ["memphis", "MEM", "Memphis", "AAC"],
  ["navy", "NAVY", "Navy", "AAC"],
  ["north-texas", "UNT", "North Texas", "AAC"],
  ["rice", "RICE", "Rice", "AAC"],
  ["south-florida", "USF", "South Florida", "AAC"],
  ["temple", "TEM", "Temple", "AAC"],
  ["tulane", "TULN", "Tulane", "AAC"],
  ["tulsa", "TLSA", "Tulsa", "AAC"],
  ["uab", "UAB", "UAB", "AAC"],
  ["utsa", "UTSA", "UTSA", "AAC"],
  // Mountain West
  ["air-force", "AFA", "Air Force", "Mountain West"],
  ["boise-state", "BSU", "Boise State", "Mountain West"],
  ["colorado-state", "CSU", "Colorado State", "Mountain West"],
  ["fresno-state", "FRES", "Fresno State", "Mountain West"],
  ["hawaii", "HAW", "Hawaii", "Mountain West"],
  ["nevada", "NEV", "Nevada", "Mountain West"],
  ["new-mexico", "UNM", "New Mexico", "Mountain West"],
  ["san-diego-state", "SDSU", "San Diego State", "Mountain West"],
  ["san-jose-state", "SJSU", "San José State", "Mountain West"],
  ["unlv", "UNLV", "UNLV", "Mountain West"],
  ["utah-state", "USU", "Utah State", "Mountain West"],
  ["wyoming", "WYO", "Wyoming", "Mountain West"],
  // Sun Belt
  ["app-state", "APP", "App State", "Sun Belt"],
  ["arkansas-state", "ARST", "Arkansas State", "Sun Belt"],
  ["coastal-carolina", "CCU", "Coastal Carolina", "Sun Belt"],
  ["georgia-southern", "GASO", "Georgia Southern", "Sun Belt"],
  ["georgia-state", "GAST", "Georgia State", "Sun Belt"],
  ["james-madison", "JMU", "James Madison", "Sun Belt"],
  ["louisiana", "UL", "Louisiana", "Sun Belt"],
  ["marshall", "MRSH", "Marshall", "Sun Belt"],
  ["old-dominion", "ODU", "Old Dominion", "Sun Belt"],
  ["south-alabama", "USA", "South Alabama", "Sun Belt"],
  ["southern-miss", "USM", "Southern Miss", "Sun Belt"],
  ["texas-state", "TXST", "Texas State", "Sun Belt"],
  ["troy", "TROY", "Troy", "Sun Belt"],
  ["ulm", "ULM", "ULM", "Sun Belt"],
  // MAC
  ["akron", "AKR", "Akron", "MAC"],
  ["ball-state", "BALL", "Ball State", "MAC"],
  ["bowling-green", "BGSU", "Bowling Green", "MAC"],
  ["buffalo", "BUFF", "Buffalo", "MAC"],
  ["central-michigan", "CMU", "Central Michigan", "MAC"],
  ["eastern-michigan", "EMU", "Eastern Michigan", "MAC"],
  ["kent-state", "KENT", "Kent State", "MAC"],
  ["miami-oh", "M-OH", "Miami (OH)", "MAC"],
  ["northern-illinois", "NIU", "Northern Illinois", "MAC"],
  ["ohio", "OHIO", "Ohio", "MAC"],
  ["toledo", "TOL", "Toledo", "MAC"],
  ["western-michigan", "WMU", "Western Michigan", "MAC"],
  // CUSA
  ["florida-international", "FIU", "FIU", "CUSA"],
  ["jacksonville-state", "JVST", "Jacksonville State", "CUSA"],
  ["kennesaw-state", "KENN", "Kennesaw State", "CUSA"],
  ["liberty", "LIB", "Liberty", "CUSA"],
  ["louisiana-tech", "LT", "Louisiana Tech", "CUSA"],
  ["middle-tennessee", "MTSU", "Middle Tennessee", "CUSA"],
  ["new-mexico-state", "NMSU", "New Mexico State", "CUSA"],
  ["sam-houston", "SHSU", "Sam Houston", "CUSA"],
  ["utep", "UTEP", "UTEP", "CUSA"],
  ["western-kentucky", "WKU", "Western Kentucky", "CUSA"],
  // Independents
  ["connecticut", "CONN", "UConn", "Independent"],
  ["massachusetts", "MASS", "UMass", "Independent"],
  ["notre-dame", "ND", "Notre Dame", "Independent"],
]);

/**
 * CBB / NCAAM — D1 directory expanded for B7 identity (#14 alias expand).
 * Unique slugs; Miami FL (ACC) ≠ Miami OH (MAC). Bare "miami" slug never used.
 * team_id grain aligns with KenPom-style aliases.json (spaces); slug uses hyphens.
 */
export const NCAAM_TEAM_DIRECTORY: TeamDirectoryEntry[] = mapTeams([
  // ACC
  ["boston-college", "BC", "Boston College", "ACC"],
  ["california", "CAL", "California", "ACC"],
  ["clemson", "CLEM", "Clemson", "ACC"],
  ["duke", "DUKE", "Duke", "ACC"],
  ["florida-state", "FSU", "Florida State", "ACC"],
  ["georgia-tech", "GT", "Georgia Tech", "ACC"],
  ["louisville", "LOU", "Louisville", "ACC"],
  ["miami-fl", "MIA", "Miami (FL)", "ACC"],
  ["nc-state", "NCSU", "NC State", "ACC"],
  ["north-carolina", "UNC", "North Carolina", "ACC"],
  ["notre-dame", "ND", "Notre Dame", "ACC"],
  ["pittsburgh", "PITT", "Pittsburgh", "ACC"],
  ["smu", "SMU", "SMU", "ACC"],
  ["stanford", "STAN", "Stanford", "ACC"],
  ["syracuse", "SYR", "Syracuse", "ACC"],
  ["virginia", "UVA", "Virginia", "ACC"],
  ["virginia-tech", "VT", "Virginia Tech", "ACC"],
  ["wake-forest", "WAKE", "Wake Forest", "ACC"],
  // Big Ten
  ["illinois", "ILL", "Illinois", "Big Ten"],
  ["indiana", "IU", "Indiana", "Big Ten"],
  ["iowa", "IOWA", "Iowa", "Big Ten"],
  ["maryland", "MD", "Maryland", "Big Ten"],
  ["michigan", "MICH", "Michigan", "Big Ten"],
  ["michigan-state", "MSU", "Michigan State", "Big Ten"],
  ["minnesota", "MINN", "Minnesota", "Big Ten"],
  ["nebraska", "NEB", "Nebraska", "Big Ten"],
  ["northwestern", "NU", "Northwestern", "Big Ten"],
  ["ohio-state", "OSU", "Ohio State", "Big Ten"],
  ["oregon", "ORE", "Oregon", "Big Ten"],
  ["penn-state", "PSU", "Penn State", "Big Ten"],
  ["purdue", "PUR", "Purdue", "Big Ten"],
  ["rutgers", "RUTG", "Rutgers", "Big Ten"],
  ["ucla", "UCLA", "UCLA", "Big Ten"],
  ["usc", "USC", "USC", "Big Ten"],
  ["washington", "WASH", "Washington", "Big Ten"],
  ["wisconsin", "WIS", "Wisconsin", "Big Ten"],
  // Big 12
  ["arizona", "ARIZ", "Arizona", "Big 12"],
  ["arizona-state", "ASU", "Arizona State", "Big 12"],
  ["baylor", "BAY", "Baylor", "Big 12"],
  ["byu", "BYU", "BYU", "Big 12"],
  ["cincinnati", "CIN", "Cincinnati", "Big 12"],
  ["colorado", "COLO", "Colorado", "Big 12"],
  ["houston", "HOU", "Houston", "Big 12"],
  ["iowa-state", "ISU", "Iowa State", "Big 12"],
  ["kansas", "KU", "Kansas", "Big 12"],
  ["kansas-state", "KSU", "Kansas State", "Big 12"],
  ["oklahoma-state", "OKST", "Oklahoma State", "Big 12"],
  ["tcu", "TCU", "TCU", "Big 12"],
  ["texas-tech", "TTU", "Texas Tech", "Big 12"],
  ["ucf", "UCF", "UCF", "Big 12"],
  ["utah", "UTAH", "Utah", "Big 12"],
  ["west-virginia", "WVU", "West Virginia", "Big 12"],
  // SEC
  ["alabama", "ALA", "Alabama", "SEC"],
  ["arkansas", "ARK", "Arkansas", "SEC"],
  ["auburn", "AUB", "Auburn", "SEC"],
  ["florida", "FLA", "Florida", "SEC"],
  ["georgia", "UGA", "Georgia", "SEC"],
  ["kentucky", "UK", "Kentucky", "SEC"],
  ["lsu", "LSU", "LSU", "SEC"],
  ["mississippi", "MISS", "Ole Miss", "SEC"],
  ["mississippi-state", "MSST", "Mississippi State", "SEC"],
  ["missouri", "MIZ", "Missouri", "SEC"],
  ["oklahoma", "OU", "Oklahoma", "SEC"],
  ["south-carolina", "SC", "South Carolina", "SEC"],
  ["tennessee", "TENN", "Tennessee", "SEC"],
  ["texas", "TEX", "Texas", "SEC"],
  ["texas-am", "TA&M", "Texas A&M", "SEC"],
  ["vanderbilt", "VAN", "Vanderbilt", "SEC"],
  // Big East
  ["butler", "BTLR", "Butler", "Big East"],
  ["creighton", "CREI", "Creighton", "Big East"],
  ["depaul", "DEP", "DePaul", "Big East"],
  ["georgetown", "GTWN", "Georgetown", "Big East"],
  ["marquette", "MARQ", "Marquette", "Big East"],
  ["providence", "PROV", "Providence", "Big East"],
  ["seton-hall", "HALL", "Seton Hall", "Big East"],
  ["st-johns", "SJU", "St. John's", "Big East"],
  ["uconn", "CONN", "UConn", "Big East"],
  ["villanova", "VILL", "Villanova", "Big East"],
  ["xavier", "XAV", "Xavier", "Big East"],
  // AAC
  ["charlotte", "CLT", "Charlotte", "AAC"],
  ["east-carolina", "ECU", "East Carolina", "AAC"],
  ["florida-atlantic", "FAU", "Florida Atlantic", "AAC"],
  ["memphis", "MEM", "Memphis", "AAC"],
  ["north-texas", "UNT", "North Texas", "AAC"],
  ["rice", "RICE", "Rice", "AAC"],
  ["south-florida", "USF", "South Florida", "AAC"],
  ["temple", "TEM", "Temple", "AAC"],
  ["tulane", "TULN", "Tulane", "AAC"],
  ["tulsa", "TLSA", "Tulsa", "AAC"],
  ["uab", "UAB", "UAB", "AAC"],
  ["utsa", "UTSA", "UTSA", "AAC"],
  ["wichita-state", "WICH", "Wichita State", "AAC"],
  // Mountain West
  ["air-force", "AF", "Air Force", "Mountain West"],
  ["boise-state", "BOIS", "Boise State", "Mountain West"],
  ["colorado-state", "CSU", "Colorado State", "Mountain West"],
  ["fresno-state", "FRES", "Fresno State", "Mountain West"],
  ["nevada", "NEV", "Nevada", "Mountain West"],
  ["new-mexico", "UNM", "New Mexico", "Mountain West"],
  ["san-diego-state", "SDSU", "San Diego State", "Mountain West"],
  ["san-jose-state", "SJSU", "San José State", "Mountain West"],
  ["unlv", "UNLV", "UNLV", "Mountain West"],
  ["utah-state", "USU", "Utah State", "Mountain West"],
  ["wyoming", "WYO", "Wyoming", "Mountain West"],
  // Atlantic 10
  ["davidson", "DAV", "Davidson", "Atlantic 10"],
  ["dayton", "DAY", "Dayton", "Atlantic 10"],
  ["duquesne", "DUQ", "Duquesne", "Atlantic 10"],
  ["fordham", "FOR", "Fordham", "Atlantic 10"],
  ["george-mason", "GMU", "George Mason", "Atlantic 10"],
  ["george-washington", "GW", "George Washington", "Atlantic 10"],
  ["la-salle", "LAS", "La Salle", "Atlantic 10"],
  ["loyola-chicago", "LUC", "Loyola Chicago", "Atlantic 10"],
  ["massachusetts", "MASS", "Massachusetts", "Atlantic 10"],
  ["rhode-island", "URI", "Rhode Island", "Atlantic 10"],
  ["richmond", "RICH", "Richmond", "Atlantic 10"],
  ["saint-josephs", "JOES", "Saint Joseph's", "Atlantic 10"],
  ["saint-louis", "SLU", "Saint Louis", "Atlantic 10"],
  ["st-bonaventure", "SBU", "St. Bonaventure", "Atlantic 10"],
  ["vcu", "VCU", "VCU", "Atlantic 10"],
  // WCC
  ["gonzaga", "GONZ", "Gonzaga", "WCC"],
  ["loyola-marymount", "LMU", "Loyola Marymount", "WCC"],
  ["oregon-state", "ORST", "Oregon State", "WCC"],
  ["pacific", "PAC", "Pacific", "WCC"],
  ["pepperdine", "PEPP", "Pepperdine", "WCC"],
  ["portland", "PORT", "Portland", "WCC"],
  ["saint-marys", "SMC", "Saint Mary's", "WCC"],
  ["san-diego", "USD", "San Diego", "WCC"],
  ["san-francisco", "SF", "San Francisco", "WCC"],
  ["santa-clara", "SCU", "Santa Clara", "WCC"],
  ["washington-state", "WSU", "Washington State", "WCC"],
  // MVC
  ["belmont", "BEL", "Belmont", "MVC"],
  ["bradley", "BRAD", "Bradley", "MVC"],
  ["drake", "DRKE", "Drake", "MVC"],
  ["evansville", "EVAN", "Evansville", "MVC"],
  ["illinois-chicago", "UIC", "UIC", "MVC"],
  ["illinois-state", "ILST", "Illinois State", "MVC"],
  ["indiana-state", "INST", "Indiana State", "MVC"],
  ["missouri-state", "MOST", "Missouri State", "MVC"],
  ["murray-state", "MUR", "Murray State", "MVC"],
  ["northern-iowa", "UNI", "Northern Iowa", "MVC"],
  ["southern-illinois", "SIU", "Southern Illinois", "MVC"],
  ["valparaiso", "VAL", "Valparaiso", "MVC"],
  // MAC
  ["akron", "AKR", "Akron", "MAC"],
  ["ball-state", "BALL", "Ball State", "MAC"],
  ["bowling-green", "BGSU", "Bowling Green", "MAC"],
  ["buffalo", "BUF", "Buffalo", "MAC"],
  ["central-michigan", "CMU", "Central Michigan", "MAC"],
  ["eastern-michigan", "EMU", "Eastern Michigan", "MAC"],
  ["kent-state", "KENT", "Kent State", "MAC"],
  ["miami-oh", "M-OH", "Miami (OH)", "MAC"],
  ["northern-illinois", "NIU", "Northern Illinois", "MAC"],
  ["ohio", "OHIO", "Ohio", "MAC"],
  ["toledo", "TOL", "Toledo", "MAC"],
  ["western-michigan", "WMU", "Western Michigan", "MAC"],
  // Conference USA
  ["fiu", "FIU", "Florida International", "Conference USA"],
  ["jacksonville-state", "JXST", "Jacksonville State", "Conference USA"],
  ["kennesaw-state", "KENN", "Kennesaw State", "Conference USA"],
  ["liberty", "LIB", "Liberty", "Conference USA"],
  ["louisiana-tech", "LT", "Louisiana Tech", "Conference USA"],
  ["middle-tennessee", "MTSU", "Middle Tennessee", "Conference USA"],
  ["new-mexico-state", "NMSU", "New Mexico State", "Conference USA"],
  ["sam-houston-state", "SHSU", "Sam Houston", "Conference USA"],
  ["utep", "UTEP", "UTEP", "Conference USA"],
  ["western-kentucky", "WKU", "Western Kentucky", "Conference USA"],
  // Sun Belt
  ["appalachian-state", "APP", "App State", "Sun Belt"],
  ["arkansas-state", "ARST", "Arkansas State", "Sun Belt"],
  ["coastal-carolina", "CCU", "Coastal Carolina", "Sun Belt"],
  ["georgia-southern", "GASO", "Georgia Southern", "Sun Belt"],
  ["georgia-state", "GAST", "Georgia State", "Sun Belt"],
  ["james-madison", "JMU", "James Madison", "Sun Belt"],
  ["louisiana", "UL", "Louisiana", "Sun Belt"],
  ["louisiana-monroe", "ULM", "UL Monroe", "Sun Belt"],
  ["marshall", "MRSH", "Marshall", "Sun Belt"],
  ["old-dominion", "ODU", "Old Dominion", "Sun Belt"],
  ["south-alabama", "USA", "South Alabama", "Sun Belt"],
  ["southern-miss", "USM", "Southern Miss", "Sun Belt"],
  ["texas-state", "TXST", "Texas State", "Sun Belt"],
  ["troy", "TROY", "Troy", "Sun Belt"],
  // CAA
  ["campbell", "CAM", "Campbell", "CAA"],
  ["charleston", "COFC", "Charleston", "CAA"],
  ["delaware", "DEL", "Delaware", "CAA"],
  ["drexel", "DREX", "Drexel", "CAA"],
  ["elon", "ELON", "Elon", "CAA"],
  ["hampton", "HAMP", "Hampton", "CAA"],
  ["hofstra", "HOF", "Hofstra", "CAA"],
  ["monmouth", "MONM", "Monmouth", "CAA"],
  ["north-carolina-at", "NCAT", "North Carolina A&T", "CAA"],
  ["northeastern", "NE", "Northeastern", "CAA"],
  ["stony-brook", "STBK", "Stony Brook", "CAA"],
  ["towson", "TOW", "Towson", "CAA"],
  ["unc-wilmington", "UNCW", "UNC Wilmington", "CAA"],
  ["william-mary", "W&M", "William & Mary", "CAA"],
  // Atlantic Sun
  ["austin-peay", "APSU", "Austin Peay", "Atlantic Sun"],
  ["bellarmine", "BELL", "Bellarmine", "Atlantic Sun"],
  ["central-arkansas", "CARK", "Central Arkansas", "Atlantic Sun"],
  ["eastern-kentucky", "EKU", "Eastern Kentucky", "Atlantic Sun"],
  ["florida-gulf-coast", "FGCU", "Florida Gulf Coast", "Atlantic Sun"],
  ["jacksonville", "JAX", "Jacksonville", "Atlantic Sun"],
  ["lipscomb", "LIP", "Lipscomb", "Atlantic Sun"],
  ["north-alabama", "UNA", "North Alabama", "Atlantic Sun"],
  ["north-florida", "UNF", "North Florida", "Atlantic Sun"],
  ["stetson", "STET", "Stetson", "Atlantic Sun"],
  ["west-georgia", "WGA", "West Georgia", "Atlantic Sun"],
  // America East
  ["albany", "UALB", "UAlbany", "America East"],
  ["binghamton", "BING", "Binghamton", "America East"],
  ["bryant", "BRY", "Bryant", "America East"],
  ["maine", "ME", "Maine", "America East"],
  ["new-hampshire", "UNH", "New Hampshire", "America East"],
  ["njit", "NJIT", "NJIT", "America East"],
  ["umass-lowell", "UML", "UMass Lowell", "America East"],
  ["umbc", "UMBC", "UMBC", "America East"],
  ["vermont", "UVM", "Vermont", "America East"],
  // Big Sky
  ["eastern-washington", "EWU", "Eastern Washington", "Big Sky"],
  ["idaho", "IDHO", "Idaho", "Big Sky"],
  ["idaho-state", "IDST", "Idaho State", "Big Sky"],
  ["montana", "MONT", "Montana", "Big Sky"],
  ["montana-state", "MTST", "Montana State", "Big Sky"],
  ["northern-arizona", "NAU", "Northern Arizona", "Big Sky"],
  ["northern-colorado", "UNCO", "Northern Colorado", "Big Sky"],
  ["portland-state", "PRST", "Portland State", "Big Sky"],
  ["sacramento-state", "SAC", "Sacramento State", "Big Sky"],
  ["weber-state", "WEB", "Weber State", "Big Sky"],
  // Big South
  ["charleston-southern", "CHSO", "Charleston Southern", "Big South"],
  ["gardner-webb", "GWEB", "Gardner-Webb", "Big South"],
  ["high-point", "HPU", "High Point", "Big South"],
  ["longwood", "LONG", "Longwood", "Big South"],
  ["presbyterian", "PRES", "Presbyterian", "Big South"],
  ["radford", "RAD", "Radford", "Big South"],
  ["unc-asheville", "UNCA", "UNC Asheville", "Big South"],
  ["usc-upstate", "UPST", "South Carolina Upstate", "Big South"],
  ["winthrop", "WIN", "Winthrop", "Big South"],
  // Big West
  ["cal-poly", "CP", "Cal Poly", "Big West"],
  ["cal-state-bakersfield", "CSUB", "Cal State Bakersfield", "Big West"],
  ["cal-state-fullerton", "CSUF", "Cal State Fullerton", "Big West"],
  ["csun", "CSUN", "Cal State Northridge", "Big West"],
  ["hawaii", "HAW", "Hawai'i", "Big West"],
  ["long-beach-state", "LBSU", "Long Beach State", "Big West"],
  ["uc-davis", "UCD", "UC Davis", "Big West"],
  ["uc-irvine", "UCI", "UC Irvine", "Big West"],
  ["uc-riverside", "UCR", "UC Riverside", "Big West"],
  ["uc-san-diego", "UCSD", "UC San Diego", "Big West"],
  ["uc-santa-barbara", "UCSB", "UC Santa Barbara", "Big West"],
  // Horizon
  ["cleveland-state", "CLE", "Cleveland State", "Horizon"],
  ["detroit-mercy", "DETM", "Detroit Mercy", "Horizon"],
  ["green-bay", "GB", "Green Bay", "Horizon"],
  ["iu-indy", "IUIN", "IU Indianapolis", "Horizon"],
  ["milwaukee", "MILW", "Milwaukee", "Horizon"],
  ["northern-kentucky", "NKU", "Northern Kentucky", "Horizon"],
  ["oakland", "OAK", "Oakland", "Horizon"],
  ["purdue-fort-wayne", "PFW", "Purdue Fort Wayne", "Horizon"],
  ["robert-morris", "RMU", "Robert Morris", "Horizon"],
  ["wright-state", "WRST", "Wright State", "Horizon"],
  ["youngstown-state", "YSU", "Youngstown State", "Horizon"],
  // Ivy
  ["brown", "BRWN", "Brown", "Ivy"],
  ["columbia", "COLU", "Columbia", "Ivy"],
  ["cornell", "COR", "Cornell", "Ivy"],
  ["dartmouth", "DART", "Dartmouth", "Ivy"],
  ["harvard", "HARV", "Harvard", "Ivy"],
  ["penn", "PENN", "Pennsylvania", "Ivy"],
  ["princeton", "PRIN", "Princeton", "Ivy"],
  ["yale", "YALE", "Yale", "Ivy"],
  // MEAC
  ["coppin-state", "COPP", "Coppin State", "MEAC"],
  ["delaware-state", "DSU", "Delaware State", "MEAC"],
  ["howard", "HOW", "Howard", "MEAC"],
  ["maryland-eastern-shore", "UMES", "Maryland Eastern Shore", "MEAC"],
  ["morgan-state", "MORG", "Morgan State", "MEAC"],
  ["norfolk-state", "NORF", "Norfolk State", "MEAC"],
  ["north-carolina-central", "NCCU", "North Carolina Central", "MEAC"],
  ["south-carolina-state", "SCST", "South Carolina State", "MEAC"],
  // NEC
  ["central-connecticut", "CCSU", "Central Connecticut", "NEC"],
  ["chicago-state", "CHST", "Chicago State", "NEC"],
  ["fairleigh-dickinson", "FDU", "Fairleigh Dickinson", "NEC"],
  ["le-moyne", "LEM", "Le Moyne", "NEC"],
  ["liu", "LIU", "Long Island University", "NEC"],
  ["mercyhurst", "MERC", "Mercyhurst", "NEC"],
  ["saint-francis", "SFPA", "Saint Francis", "NEC"],
  ["stonehill", "STO", "Stonehill", "NEC"],
  ["wagner", "WAG", "Wagner", "NEC"],
  // OVC
  ["eastern-illinois", "EIU", "Eastern Illinois", "OVC"],
  ["lindenwood", "LIN", "Lindenwood", "OVC"],
  ["little-rock", "LR", "Little Rock", "OVC"],
  ["morehead-state", "MORE", "Morehead State", "OVC"],
  ["siue", "SIUE", "SIU Edwardsville", "OVC"],
  ["southeast-missouri", "SEMO", "Southeast Missouri State", "OVC"],
  ["southern-indiana", "USI", "Southern Indiana", "OVC"],
  ["tennessee-martin", "UTM", "UT Martin", "OVC"],
  ["tennessee-state", "TNST", "Tennessee State", "OVC"],
  ["tennessee-tech", "TNTC", "Tennessee Tech", "OVC"],
  ["western-illinois", "WIU", "Western Illinois", "OVC"],
  // Patriot
  ["american", "AMER", "American University", "Patriot"],
  ["army", "ARMY", "Army", "Patriot"],
  ["boston-university", "BU", "Boston University", "Patriot"],
  ["bucknell", "BUCK", "Bucknell", "Patriot"],
  ["colgate", "COLG", "Colgate", "Patriot"],
  ["holy-cross", "HC", "Holy Cross", "Patriot"],
  ["lafayette", "LAF", "Lafayette", "Patriot"],
  ["lehigh", "LEH", "Lehigh", "Patriot"],
  ["loyola-md", "L-MD", "Loyola Maryland", "Patriot"],
  ["navy", "NAVY", "Navy", "Patriot"],
  // Southern
  ["chattanooga", "UTC", "Chattanooga", "Southern"],
  ["east-tennessee-state", "ETSU", "East Tennessee State", "Southern"],
  ["furman", "FUR", "Furman", "Southern"],
  ["mercer", "MER", "Mercer", "Southern"],
  ["samford", "SAM", "Samford", "Southern"],
  ["the-citadel", "CIT", "The Citadel", "Southern"],
  ["unc-greensboro", "UNCG", "UNC Greensboro", "Southern"],
  ["vmi", "VMI", "VMI", "Southern"],
  ["western-carolina", "WCU", "Western Carolina", "Southern"],
  ["wofford", "WOF", "Wofford", "Southern"],
  // Southland
  ["east-texas-am", "ETAM", "East Texas A&M", "Southland"],
  ["houston-christian", "HCU", "Houston Christian", "Southland"],
  ["incarnate-word", "UIW", "Incarnate Word", "Southland"],
  ["lamar", "LAM", "Lamar", "Southland"],
  ["mcneese", "MCN", "McNeese", "Southland"],
  ["new-orleans", "NOLA", "LSU New Orleans", "Southland"],
  ["nicholls", "NICH", "Nicholls", "Southland"],
  ["northwestern-state", "NWST", "Northwestern State", "Southland"],
  ["southeastern-louisiana", "SELA", "SE Louisiana", "Southland"],
  ["stephen-f-austin", "SFA", "Stephen F. Austin", "Southland"],
  ["texas-am-cc", "AMCC", "Texas A&M-Corpus Christi", "Southland"],
  ["ut-rio-grande-valley", "RGV", "UT Rio Grande Valley", "Southland"],
  // SWAC
  ["alabama-am", "AAMU", "Alabama A&M", "SWAC"],
  ["alabama-state", "ALST", "Alabama State", "SWAC"],
  ["alcorn-state", "ALCN", "Alcorn State", "SWAC"],
  ["arkansas-pine-bluff", "UAPB", "Arkansas-Pine Bluff", "SWAC"],
  ["bethune-cookman", "BCU", "Bethune-Cookman", "SWAC"],
  ["florida-am", "FAMU", "Florida A&M", "SWAC"],
  ["grambling-state", "GRAM", "Grambling", "SWAC"],
  ["jackson-state", "JKST", "Jackson State", "SWAC"],
  ["mississippi-valley-state", "MVSU", "Mississippi Valley State", "SWAC"],
  ["prairie-view-am", "PV", "Prairie View A&M", "SWAC"],
  ["southern", "SOU", "Southern", "SWAC"],
  ["texas-southern", "TXSO", "Texas Southern", "SWAC"],
  // Summit
  ["denver", "DEN", "Denver", "Summit"],
  ["kansas-city", "KC", "Kansas City", "Summit"],
  ["nebraska-omaha", "OMA", "Omaha", "Summit"],
  ["north-dakota", "UND", "North Dakota", "Summit"],
  ["north-dakota-state", "NDSU", "North Dakota State", "Summit"],
  ["oral-roberts", "ORU", "Oral Roberts", "Summit"],
  ["south-dakota", "SDAK", "South Dakota", "Summit"],
  ["south-dakota-state", "SDST", "South Dakota State", "Summit"],
  ["st-thomas", "STMN", "St. Thomas", "Summit"],
  // United Athletic
  ["abilene-christian", "ACU", "Abilene Christian", "United Athletic"],
  ["cal-baptist", "CBU", "California Baptist", "United Athletic"],
  ["grand-canyon", "GCU", "Grand Canyon", "United Athletic"],
  ["seattle", "SEA", "Seattle U", "United Athletic"],
  ["southern-utah", "SUU", "Southern Utah", "United Athletic"],
  ["tarleton-state", "TAR", "Tarleton State", "United Athletic"],
  ["ut-arlington", "UTA", "UT Arlington", "United Athletic"],
  ["utah-tech", "UTU", "Utah Tech", "United Athletic"],
  ["utah-valley", "UVU", "Utah Valley", "United Athletic"],
  ["queens", "QUE", "Queens", "United Athletic"],
  // Metro
  ["canisius", "CAN", "Canisius", "Metro"],
  ["fairfield", "FAIR", "Fairfield", "Metro"],
  ["iona", "IONA", "Iona", "Metro"],
  ["manhattan", "MAN", "Manhattan", "Metro"],
  ["marist", "MRST", "Marist", "Metro"],
  ["merrimack", "MRMK", "Merrimack", "Metro"],
  ["mount-st-marys", "MSM", "Mount St. Mary's", "Metro"],
  ["niagara", "NIA", "Niagara", "Metro"],
  ["quinnipiac", "QUIN", "Quinnipiac", "Metro"],
  ["rider", "RID", "Rider", "Metro"],
  ["sacred-heart", "SHU", "Sacred Heart", "Metro"],
  ["saint-peters", "SPU", "Saint Peter's", "Metro"],
  ["siena", "SIE", "Siena", "Metro"],
  // D1
  ["new-haven", "NHVN", "New Haven", "D1"],
]);
