"""NHL season engine package (Ch1–Ch3 + Ch5 PlayerProjection)."""

from src.services.nhl_season_engine.priors import (
    ENGINE_VERSION,
    NHL_GOALIE_TANDEM_SHARE_SUM,
    NHL_SITUATION_GOAL_CAP,
    NHL_TEAM_CARRY_SHRINK,
    NHL_TEAM_REBASE_RESIDUAL_CAP,
    NHL_TOI_GRID_SKATER_MINUTES,
    ODDS_SPORT_KEY,
    PAPER_SIM_S_SET,
    PLAYER_YEAR_WEIGHTS,
    PLAYER_YEAR_WEIGHTS_BY_SEASON_ID,
    PROP_PLAY_CAP_PER_SLATE,
    STARTER_GATE,
)
from src.services.nhl_season_engine.team_prior import (
    apply_nhl_team_carry_shrink,
    documentation as team_prior_documentation,
    get_team_prior,
    load_team_prior_pack,
)
from src.services.nhl_season_engine.toi_grid import (
    documentation as toi_grid_documentation,
    get_team_goalie_tandem,
    get_team_toi,
    load_goalie_tandem,
    load_toi_grid,
)
from src.services.nhl_season_engine.player_projection import (
    GOALIE_VECTOR_KEYS,
    SKATER_VECTOR_KEYS,
    documentation as player_projection_documentation,
    get_goalie_projection,
    get_skater_projection,
    get_team_goalies,
    get_team_skaters,
    load_player_projection_pack,
    team_g_identity,
)
from src.services.nhl_season_engine.situation import (
    apply_situation_player_projections,
    apply_situation_team_line,
    documentation as situation_documentation,
    get_team_game_flags,
    load_paper_sim,
    load_schedule_pack,
    load_situation_coeffs,
    load_venue_flags,
    situation_delta_goals,
)

__all__ = [
    "ENGINE_VERSION",
    "NHL_TEAM_CARRY_SHRINK",
    "NHL_TEAM_REBASE_RESIDUAL_CAP",
    "NHL_SITUATION_GOAL_CAP",
    "NHL_TOI_GRID_SKATER_MINUTES",
    "NHL_GOALIE_TANDEM_SHARE_SUM",
    "PAPER_SIM_S_SET",
    "PLAYER_YEAR_WEIGHTS",
    "PLAYER_YEAR_WEIGHTS_BY_SEASON_ID",
    "PROP_PLAY_CAP_PER_SLATE",
    "ODDS_SPORT_KEY",
    "STARTER_GATE",
    "apply_nhl_team_carry_shrink",
    "get_team_prior",
    "load_team_prior_pack",
    "team_prior_documentation",
    "load_toi_grid",
    "load_goalie_tandem",
    "get_team_toi",
    "get_team_goalie_tandem",
    "toi_grid_documentation",
    "SKATER_VECTOR_KEYS",
    "GOALIE_VECTOR_KEYS",
    "load_player_projection_pack",
    "get_skater_projection",
    "get_goalie_projection",
    "get_team_skaters",
    "get_team_goalies",
    "team_g_identity",
    "player_projection_documentation",
    "load_situation_coeffs",
    "load_schedule_pack",
    "load_venue_flags",
    "load_paper_sim",
    "get_team_game_flags",
    "situation_delta_goals",
    "apply_situation_team_line",
    "apply_situation_player_projections",
    "situation_documentation",
]
